---
root: true
env:
  node: true
  jest: true
  es6: true
  browser: false
plugins:
  - '@typescript-eslint'
  - prettier
  - deprecation
  - import
  - unicorn
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: true
ignorePatterns:
  - 'dist/'
  - 'node_modules/'
  - 'coverage/'
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
rules:
  no-return-await: 'error'
  unicorn/filename-case:
    - error
    - case: kebabCase
  deprecation/deprecation: warn
  import/no-unresolved: error
  import/no-extraneous-dependencies:
    - error
