services:
  prestashop:
    container_name: prestashop
    restart: unless-stopped
    image: prestashop/prestashop-flashlight:${SHOP_VERSION}
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
      ps-accounts-downloader:
        condition: service_completed_successfully
    environment:
      - SSL_REDIRECT=true
      - INSTALL_MODULES_DIR=/modules/downloads/auto-install
    volumes:
      - ./modules:/modules
      - ./init-scripts:/tmp/init-scripts:ro
    ports:
      - ${HOST_PORT_BIND_PRESTASHOP:?See e2e-env/.env.dist}:80

  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mariadb:lts
    environment:
      - TZ=Europe/Paris
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '--host=localhost',
          '--user=prestashop',
          '--password=prestashop',
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    command: [ 'mysqld' ]

  mytun-config:
    container_name: mytun-config
    restart: 'no'
    env_file: .env
    extends:
      file: myTun/docker-compose.yml
      service: config-generator

  mytun:
    container_name: mytun
    restart: always
    image: cloudflare/cloudflared:latest
    command: tunnel --config /config.yml run
    depends_on:
      mytun-config:
        condition: service_completed_successfully
    volumes:
      - ./myTun/config/mytun-config.yml:/config.yml
      - ./myTun/config/mytun-credentials.json:/credentials.json

  ps-accounts-downloader:
    container_name: ps-accounts-downloader
    restart: 'no'
    env_file: .env
    extends:
      file: modules/docker-compose.yml
      service: asset-downloader
    volumes:
      - ./modules/downloads/auto-install:/modules/downloads/auto-install:rw
    environment:
      GITHUB_API_TOKEN: $GITHUB_API_TOKEN
      GITHUB_REPOSITORY: PrestaShopCorp/ps_accounts
      TARGET_VERSION: $PS_ACCOUNTS_VERSION
      TARGET_ASSET: ps_accounts.zip
      FINAL_ASSET: ps_accounts-${PS_ACCOUNTS_VERSION}.zip
      ASSET_PATH: /modules/downloads/auto-install
