services:
  ps-accounts-downloader:
    restart: 'no'
    env_file: .env
    extends:
      file: ./modules/docker-compose.yml
      service: asset-downloader
    volumes:
      - ./modules:/modules:rw
    environment:
      GITHUB_REPOSITORY: PrestaShopCorp/ps_accounts
      TARGET_VERSION: $PS_ACCOUNTS_VERSION
      TARGET_ASSET: ps_accounts_preprod.zip
      FINAL_ASSET: ps_accounts-${PS_ACCOUNTS_VERSION}_preprod.zip
      ASSET_PATH: /modules/downloads/auto-install

  mysql:
    image: mariadb:${DOCKER_VERSION_MARIADB:?See e2e-env/.env.dist}
    restart: unless-stopped
    container_name: mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '--host=localhost',
          '--user=prestashop',
          '--password=prestashop',
        ]
      interval: 1s
      timeout: 10s
      retries: 30
    ports:
      - ${HOST_PORT_BIND_MYSQL:?See e2e-env/.env.dist}:3306

  prestashop:
    image: ${DOCKER_IMAGE_PRESTASHOP:?See e2e-env/.env.dist}
    container_name: prestashop
    restart: unless-stopped
    env_file: .env
    depends_on:
      ps-accounts-downloader:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy
    environment:
      - SSL_REDIRECT=true
      - INSTALL_MODULES_DIR=/modules/downloads/auto-install
    volumes:
      - ./modules:/modules
    ports:
      - ${HOST_PORT_BIND_PRESTASHOP:?See e2e-env/.env.dist}:80

  mytun-config:
    restart: 'no'
    env_file: .env
    extends:
      file: ./myTun/docker-compose.yml
      service: config-generator

  mytun:
    restart: always
    image: cloudflare/cloudflared:latest
    command: tunnel --config /config.yml run
    depends_on:
      mytun-config:
        condition: service_completed_successfully
    volumes:
      - ./myTun/config/mytun-config.yml:/config.yml
      - ./myTun/config/mytun-credentials.json:/credentials.json

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - ${HOST_PORT_BIND_PHP_MY_ADMIN:?See e2e-env/.env.dist}:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=prestashop
      - PMA_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop

volumes:
  modules:
    driver: local
