---

services:
  asset-downloader:
    build:
      context: .
      dockerfile: ./asset-downloader.Dockerfile
    volumes:
      - ./modules/downloads/auto-install:/modules/downloads/auto-install:rw
    environment:
      - PS_ACCOUNTS_VERSION=${PS_ACCOUNTS_VERSION:?See e2e-env/.env.dist}
