name: Check

on:
  pull_request:

env:
  NODE_VERSION: 18.x

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check version

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check if version has been updated
        uses: EndBug/version-check@v2

  lint:
    runs-on: ubuntu-latest
    name: ESLint

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm i

      - name: Check eslint errors
        run: npm run lint