name: Draft release

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 18.x

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get version from package.json
        id: get_tag
        run: echo ::set-output name=PACKAGE_VERSION::$(node -p "require('./package.json').version")
      
      - name: Create a release draft
        uses: toolmantim/release-drafter@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update the version of the release
        run : gh release edit ${{ env.PACKAGE_VERSION }} --draft=true