name: NPM Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag to create release from
        required: true
        type: string
        default: 2.1.0

env:
  NODE_VERSION: 18.x
  PNPM_VERSION: 9.0.6

jobs:
  npm-publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: |
          npm install -g pnpm@${{ env.PNPM_VERSION }}
          pnpm install --no-optional

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Update pnpm version
        run: pnpm version $VERSION --no-git-tag-version --allow-same-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ env.TAG_NAME }}

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
