name: Release

on:
  release:
    types: [published]

env:
  NODE_VERSION: 18.x

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Release on NPM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: |
          npm install -g pnpm@${{ env.PNPM_VERSION }}
          pnpm install --no-optional

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Update pnpm version
        run: pnpm version $VERSION --no-git-tag-version --allow-same-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ github.event.release.tag_name }}

      - name: Publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
