---
services:
  config-generator:
    build:
      context: .
      dockerfile: ./config-generator.Dockerfile
    volumes:
      - ./config:/config:rw
    environment:
      - ACCOUNT_TAG=${ACCOUNT_TAG:?See e2e-env/.env.dist}
      - TUNNEL_SECRET=${TUNNEL_SECRET:?See e2e-env/.env.dist}
      - TUNNEL_ID=${TUNNEL_ID:?See e2e-env/.env.dist}
